// Localized name pools for nemesis bots by country/region
export const NEMESIS_NAMES = {
  default: ['Marcus', 'Jake', 'Ryan', 'Kyle', 'Derek', 'Brandon', 'Justin', 'Austin', 'Tyler', 'Shane', 'Kevin', 'Chris', 'Nathan', 'Jordan', 'Alex', 'Sarah', 'Jessica', 'Jennifer', 'Emily', 'Amanda'],
  Canada: ['Connor', 'Liam', 'Nathan', 'Mason', 'Ethan', 'Jacob', 'Logan', 'Olivia', 'Emma', 'Sophia'],
  Mexico: ['Carlos', 'Juan', 'Miguel', 'Antonio', 'Diego', 'María', 'Carmen', 'Rosa', 'Guadalupe', 'Dolores'],
  Brazil: ['Lucas', 'Felipe', 'Rafael', 'Bruno', 'Diego', 'Maria', 'Ana', 'Fernanda', 'Paula', 'Julia'],
  Argentina: ['Martín', 'Santiago', 'Lucas', 'Andrés', 'Javier', 'Valentina', 'Sofía', 'Martina', 'María', 'Camila'],
  Chile: ['Cristián', 'Raúl', 'Javier', 'Carlos', 'Diego', 'Roxana', 'Carla', 'Jimena', 'Pamela', 'Lorena'],
  Colombia: ['Juan', 'Carlos', 'Miguel', 'José', 'Fernando', 'Catalina', 'Mariana', 'Valentina', 'Adriana', 'Patricia'],
  Peru: ['Javier', 'Carlos', 'Raúl', 'Miguel', 'Juan', 'Beatriz', 'María', 'Rosa', 'Claudia', 'Patricia'],
  'United Kingdom': ['Oliver', 'George', 'Harry', 'Jack', 'Jacob', 'Olivia', 'Amelia', 'Isla', 'Emily', 'Jessica'],
  France: ['Pierre', 'Jean', 'Michel', 'André', 'Alain', 'Marie', 'Jacqueline', 'Francine', 'Christine', 'Nicole'],
  Germany: ['Klaus', 'Hans', 'Günter', 'Dieter', 'Horst', 'Margot', 'Ursula', 'Ingrid', 'Gisela', 'Petra'],
  Italy: ['Marco', 'Giuseppe', 'Giovanni', 'Mario', 'Franco', 'Maria', 'Rosa', 'Anna', 'Lucia', 'Francesca'],
  Spain: ['José', 'Juan', 'Carlos', 'Antonio', 'Miguel', 'María', 'Carmen', 'Paz', 'Dolores', 'Rosario'],
  Netherlands: ['Jan', 'Piet', 'Henk', 'Bert', 'Kees', 'Maria', 'Annie', 'Greet', 'Henny', 'Ingrid'],
  Switzerland: ['Kurt', 'Hans', 'Jürg', 'Peter', 'Klaus', 'Monika', 'Claudia', 'Anita', 'Beatrice', 'Christa'],
  Belgium: ['Dirk', 'Filip', 'Marc', 'Bart', 'Jan', 'Hanne', 'Katrien', 'Liesbeth', 'Natasja', 'Petra'],
  Austria: ['Franz', 'Josef', 'Anton', 'Karl', 'Günter', 'Grete', 'Hilde', 'Irmgard', 'Käthe', 'Liesl'],
  Portugal: ['João', 'José', 'Manuel', 'Francisco', 'Nuno', 'Amélia', 'Fátima', 'Gracinda', 'Hermínia', 'Joana'],
  Poland: ['Jan', 'Piotr', 'Stanisław', 'Andrzej', 'Jerzy', 'Maria', 'Anna', 'Zofia', 'Helena', 'Krystyna'],
  'Czech Republic': ['Jan', 'Jiří', 'Petr', 'Josef', 'Pavel', 'Maria', 'Anna', 'Božena', 'Helena', 'Hana'],
  Hungary: ['János', 'István', 'József', 'Sándor', 'György', 'Maria', 'Anna', 'Margit', 'Mária', 'Erzsébet'],
  Greece: ['Γιάννης', 'Κωνσταντίνος', 'Νικόλαος', 'Δημήτριος', 'Παναγιώτης', 'Μαρία', 'Κατερίνα', 'Ελένη', 'Άννα', 'Παναγιώτα'],
  'United Arab Emirates': ['محمد', 'علي', 'أحمد', 'سالم', 'خليفة', 'فاطمة', 'عائشة', 'ليلى', 'نور', 'سارة'],
  'Saudi Arabia': ['محمد', 'أحمد', 'علي', 'عبدالرحمن', 'خالد', 'فاطمة', 'نور', 'جميلة', 'صفية', 'زينب'],
  Israel: ['David', 'Michael', 'Moshe', 'Yisrael', 'Yosef', 'Rachel', 'Leah', 'Miriam', 'Esther', 'Sarah'],
  Qatar: ['محمد', 'أحمد', 'علي', 'ياسر', 'خليفة', 'فاطمة', 'أسماء', 'جميلة', 'نور', 'صفية'],
  Turkey: ['Mehmet', 'Ahmet', 'Ali', 'Fatih', 'Mustafa', 'Fatiha', 'Ayşe', 'Türkan', 'Seher', 'Emel'],
  Japan: ['田中', '鈴木', '佐藤', '高橋', '渡辺', '花子', '由美', '美咲', '桜', '美樹'],
  China: ['王', '李', '张', '刘', '陈', '娜', '娟', '芳', '敏', '静'],
  'South Korea': ['김', '이', '박', '최', '정', '순', '미영', '수진', '영미', '현순'],
  Singapore: ['David', 'Michael', 'James', 'Peter', 'John', 'Sarah', 'Mary', 'Lisa', 'Emma', '花'],
  'Hong Kong': ['David', 'Michael', 'John', 'Thomas', 'Wong', 'Sarah', 'Mary', 'Emily', 'Ann', '林'],
  India: ['राज', 'विजय', 'अजय', 'संजय', 'राहुल', 'प्रिया', 'शीला', 'नीता', 'गीता', 'अर्चना'],
  Thailand: ['วิทย์', 'สมิตร', 'ธนัน', 'ประเสริฐ', 'อนันต์', 'น้อย', 'ลำเจียก', 'แก้ว', 'ปาริชาติ', 'กรรณิการ์'],
  Vietnam: ['Nguyễn', 'Trần', 'Phạm', 'Hoàng', 'Phan', 'Hương', 'Hồng', 'Linh', 'Xuân', 'Hà'],
  Philippines: ['Jose', 'Juan', 'Miguel', 'Pedro', 'Ramon', 'Maria', 'Rosa', 'Carmen', 'Aurora', 'Amor'],
  Indonesia: ['Budi', 'Ahmad', 'Bambang', 'Wahyu', 'Sukarno', 'Dewi', 'Siti', 'Nur', 'Aisyah', 'Ratna'],
  Malaysia: ['Ahmad', 'Encik', 'Ramli', 'Samad', 'Taha', 'Fatimah', 'Zaitun', 'Kalimah', 'Noor', 'Nur'],
  'South Africa': ['Thabo', 'Sipho', 'Bongani', 'Mandla', 'Jabu', 'Ntombifuthi', 'Busiswa', 'Lindiwe', 'Nomsa', 'Thandi'],
  Nigeria: ['Adebayo', 'Chukwu', 'Oluwaseun', 'Tunde', 'Bolarinwa', 'Adeola', 'Zainab', 'Folake', 'Yetunde', 'Bimbo'],
  Egypt: ['محمود', 'أحمد', 'علي', 'عبدالله', 'عبدالرحمن', 'فاطمة', 'سارة', 'ليلى', 'نور', 'أمل'],
  Kenya: ['James', 'Kariuki', 'Omondi', 'Kipchoge', 'Kimani', 'Agnes', 'Joyce', 'Jane', 'Lucy', 'Susan'],
  Morocco: ['محمد', 'أحمد', 'علي', 'عبدالله', 'سالم', 'فاطمة', 'أسماء', 'زينب', 'سارة', 'ليلى'],
  Australia: ['James', 'John', 'Robert', 'Michael', 'William', 'Mary', 'Margaret', 'Patricia', 'Jennifer', 'Linda'],
  'New Zealand': ['James', 'John', 'Andrew', 'Michael', 'David', 'Mary', 'Elizabeth', 'Margaret', 'Patricia', 'Jennifer'],
};

export const NEMESIS_SURNAMES = {
  default: ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez'],
  Canada: ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Miller', 'Davis', 'Wilson', 'Anderson', 'Taylor'],
  Mexico: ['García', 'Martínez', 'López', 'Rodríguez', 'Sánchez', 'Pérez', 'Hernández', 'Domínguez', 'Ramírez', 'Morales'],
  Brazil: ['Silva', 'Santos', 'Oliveira', 'Souza', 'Costa', 'Alves', 'Gomes', 'Pereira', 'Martins', 'Ferreira'],
  Argentina: ['García', 'Martínez', 'López', 'Rodríguez', 'Fernández', 'González', 'Díaz', 'Pérez', 'Sánchez', 'Gutiérrez'],
  Chile: ['García', 'Martínez', 'González', 'López', 'Rodríguez', 'Fernández', 'Sánchez', 'Díaz', 'Peña', 'Moreno'],
  Colombia: ['García', 'Martínez', 'López', 'Rodríguez', 'Sánchez', 'Pérez', 'Hernández', 'Morales', 'Flores', 'Jiménez'],
  Peru: ['García', 'López', 'Martínez', 'Rodríguez', 'Sánchez', 'Pérez', 'González', 'Flores', 'Díaz', 'Morales'],
  'United Kingdom': ['Smith', 'Jones', 'Williams', 'Brown', 'Taylor', 'Johnson', 'Miller', 'Wilson', 'Moore', 'Anderson'],
  France: ['Dupont', 'Durand', 'Petit', 'Martin', 'Bernard', 'Thomas', 'Robert', 'Richard', 'Pacaud', 'Fournier'],
  Germany: ['Müller', 'Schmidt', 'Schneider', 'Fischer', 'Weber', 'Meyer', 'Wagner', 'Becker', 'Schulz', 'Hoffmann'],
  Italy: ['Rossi', 'Russo', 'Ferrari', 'Esposito', 'Bianchi', 'Romano', 'Colombo', 'Rizzo', 'Marino', 'Greco'],
  Spain: ['García', 'López', 'González', 'Rodríguez', 'Martínez', 'Hernández', 'Pérez', 'Sánchez', 'Díaz', 'Fernández'],
  Netherlands: ['de Vries', 'van den Berg', 'van Dijk', 'Jansen', 'Janssen', 'Peeters', 'Maes', 'Claes', 'Claeys', 'Mertens'],
  Switzerland: ['Müller', 'Meier', 'Schmid', 'Schneider', 'Keller', 'Weber', 'Meyer', 'Schmitz', 'Richter', 'Krämer'],
  Belgium: ['Claes', 'Mertens', 'Peeters', 'Maes', 'Cools', 'Vermeersch', 'Claeys', 'Vandenberghe', 'Verbeeck', 'Vermeiren'],
  Austria: ['Gruber', 'Hofer', 'Huber', 'Mayr', 'Steiner', 'Wimmer', 'Stangl', 'Sattler', 'Schauer', 'Schäffler'],
  Portugal: ['Silva', 'Santos', 'Oliveira', 'Costa', 'Pereira', 'Gomes', 'Alves', 'Lopes', 'Nunes', 'Freitas'],
  Poland: ['Novak', 'Lewandowski', 'Kamiński', 'Wojcik', 'Kucharski', 'Mazur', 'Nowak', 'Pawlak', 'Szymczyk', 'Tomaszewski'],
  'Czech Republic': ['Svoboda', 'Novotný', 'Dvořák', 'Černý', 'Pospíšil', 'Šimek', 'Procházka', 'Prchal', 'Kroupa', 'Krejčí'],
  Hungary: ['Nagy', 'Kovács', 'Molnár', 'Tóth', 'Szabo', 'Horváth', 'Varga', 'Kiss', 'Kovácsné', 'Lakatos'],
  Greece: ['Papadopoulos', 'Papadopouli', 'Papadopoulou', 'Papageorgiou', 'Papakostandin', 'Papademetriou', 'Papageorgiou', 'Papagiannakis', 'Papafilippou', 'Papagiannopoulos'],
  'United Arab Emirates': ['الحمادي', 'المهيري', 'القاسمي', 'المعلا', 'المنصوري', 'الظاهري', 'العريان', 'الكتبي', 'الطاهر', 'العمادي'],
  'Saudi Arabia': ['الأحمد', 'السعودي', 'الشمري', 'الشهري', 'الشايع', 'الشمال', 'الشهيل', 'الشهيم', 'الشهيه', 'الشهراني'],
  Israel: ['Cohen', 'Levi', 'Aharoni', 'Bar', 'Ben', 'Gal', 'Gross', 'Gold', 'Green', 'Gur'],
  Qatar: ['الدوحاني', 'الدعاني', 'القطري', 'الكعبي', 'الكواري', 'الكويتي', 'الكناني', 'الخاني', 'الدعاني', 'الدعيبي'],
  Turkey: ['Yılmaz', 'Kaya', 'Demir', 'Çetin', 'Aydın', 'Koç', 'Öztürk', 'Kaplan', 'Arslan', 'Şahin'],
  Japan: ['田中', '鈴木', '佐藤', '高橋', '渡辺', '中村', '小林', '加藤', '伊藤', '山田'],
  China: ['王', '李', '张', '刘', '陈', '杨', '黄', '周', '吴', '徐'],
  'South Korea': ['김', '이', '박', '최', '정', '강', '조', '윤', '장', '임'],
  Singapore: ['Lim', 'Tan', 'Lee', 'Wong', 'Ng', 'Chan', 'Chua', 'Teo', 'Goh', 'Yeo'],
  'Hong Kong': ['Chan', 'Wong', 'Lim', 'Tan', 'Lee', 'Ng', 'Chua', 'Teo', 'Goh', 'Yeo'],
  India: ['कुमार', 'सिंह', 'शर्मा', 'गुप्ता', 'शुक्ला', 'वर्मा', 'पांडे', 'मिश्र', 'दुबे', 'नायर'],
  Thailand: ['สวนใจ', 'สุขสวัสดิ์', 'สวนไสยศรี', 'สวนชมพู่', 'สวนครม', 'สวนไทย', 'สวนพันธ์', 'สวนพูน', 'สวนพร', 'สวนพรา'],
  Vietnam: ['Nguyễn', 'Trần', 'Phạm', 'Hoàng', 'Phan', 'Vũ', 'Đặng', 'Bùi', 'Dương', 'Lý'],
  Philippines: ['Reyes', 'Cruz', 'Santos', 'Garcia', 'Rodriguez', 'Dela Cruz', 'Tan', 'Lim', 'Wong', 'Francisco'],
  Indonesia: ['Subandrio', 'Sukarno', 'Soemitro', 'Sutrisno', 'Sukartoyo', 'Sudarsono', 'Sudarman', 'Sudaryanto', 'Sudarto', 'Sudaryono'],
  Malaysia: ['Abdullah', 'Ahmad', 'Aziz', 'Azlan', 'Ali', 'Anwar', 'Ariffin', 'Arsyad', 'Arshad', 'Asraf'],
  'South Africa': ['Mbeki', 'Mandela', 'Mkhize', 'Molefe', 'Motlanthe', 'Motshekga', 'Motsoaledi', 'Moti', 'Moti', 'Motlanthe'],
  Nigeria: ['Adeyemi', 'Adeyinka', 'Adeleke', 'Adelusi', 'Adelowo', 'Adeloye', 'Adelson', 'Adelsio', 'Adelstein', 'Adelstrom'],
  Egypt: ['عبدالله', 'محمود', 'أحمد', 'علي', 'عبدالرحمن', 'سالم', 'ياسر', 'حسن', 'إسماعيل', 'يوسف'],
  Kenya: ['Kipchoge', 'Kamau', 'Kariuki', 'Kiplagat', 'Kilonzo', 'Kinyanjui', 'Kimani', 'Kipchirchir', 'Kipngetich', 'Kipngelei'],
  Morocco: ['محمود', 'أحمد', 'علي', 'عبدالله', 'سالم', 'يوسف', 'إبراهيم', 'حسن', 'فاروق', 'محمد'],
  Australia: ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Miller', 'Davis', 'Wilson', 'Moore', 'Taylor'],
  'New Zealand': ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Miller', 'Davis', 'Wilson', 'Moore', 'Taylor'],
};