const STATES_DATA = [
  { name: "Alabama", capital: "Montgomery", cities: ["Montgomery", "Birmingham"] },
  { name: "Alaska", capital: "Juneau", cities: ["Juneau", "Anchorage"] },
  { name: "Arizona", capital: "Phoenix", cities: ["Phoenix", "Tucson"] },
  { name: "Arkansas", capital: "Little Rock", cities: ["Little Rock", "Fayetteville"] },
  { name: "California", capital: "Sacramento", cities: ["Sacramento", "Los Angeles", "San Diego", "San Francisco", "Oakland"] },
  { name: "Colorado", capital: "Denver", cities: ["Denver", "Colorado Springs"] },
  { name: "Connecticut", capital: "Hartford", cities: ["Hartford", "New Haven"] },
  { name: "Delaware", capital: "Dover", cities: ["Dover", "Wilmington"] },
  { name: "Florida", capital: "Tallahassee", cities: ["Tallahassee", "Miami", "Orlando", "Tampa Bay", "Jacksonville"] },
  { name: "Georgia", capital: "Atlanta", cities: ["Atlanta", "Savannah"] },
  { name: "Hawaii", capital: "Honolulu", cities: ["Honolulu", "Hilo"] },
  { name: "Idaho", capital: "Boise", cities: ["Boise", "Idaho Falls"] },
  { name: "Illinois", capital: "Springfield", cities: ["Springfield", "Chicago"] },
  { name: "Indiana", capital: "Indianapolis", cities: ["Indianapolis", "Fort Wayne"] },
  { name: "Iowa", capital: "Des Moines", cities: ["Des Moines", "Cedar Rapids"] },
  { name: "Kansas", capital: "Topeka", cities: ["Topeka", "Wichita", "Kansas City"] },
  { name: "Kentucky", capital: "Frankfort", cities: ["Frankfort", "Louisville", "Lexington"] },
  { name: "Louisiana", capital: "Baton Rouge", cities: ["Baton Rouge", "New Orleans"] },
  { name: "Maine", capital: "Augusta", cities: ["Augusta", "Portland"] },
  { name: "Maryland", capital: "Annapolis", cities: ["Annapolis", "Baltimore"] },
  { name: "Massachusetts", capital: "Boston", cities: ["Boston", "Worcester"] },
  { name: "Michigan", capital: "Lansing", cities: ["Lansing", "Detroit"] },
  { name: "Minnesota", capital: "Saint Paul", cities: ["Saint Paul", "Minneapolis"] },
  { name: "Mississippi", capital: "Jackson", cities: ["Jackson", "Gulfport"] },
  { name: "Missouri", capital: "Jefferson City", cities: ["Jefferson City", "St. Louis", "Kansas City"] },
  { name: "Montana", capital: "Helena", cities: ["Helena", "Billings"] },
  { name: "Nebraska", capital: "Lincoln", cities: ["Lincoln", "Omaha"] },
  { name: "Nevada", capital: "Carson City", cities: ["Carson City", "Las Vegas"] },
  { name: "New Hampshire", capital: "Concord", cities: ["Concord", "Manchester"] },
  { name: "New Jersey", capital: "Trenton", cities: ["Trenton", "Newark"] },
  { name: "New Mexico", capital: "Santa Fe", cities: ["Santa Fe", "Albuquerque"] },
  { name: "New York", capital: "Albany", cities: ["Albany", "New York City", "Bronx"] },
  { name: "North Carolina", capital: "Raleigh", cities: ["Raleigh", "Charlotte"] },
  { name: "North Dakota", capital: "Bismarck", cities: ["Bismarck", "Fargo"] },
  { name: "Ohio", capital: "Columbus", cities: ["Columbus", "Cleveland"] },
  { name: "Oklahoma", capital: "Oklahoma City", cities: ["Oklahoma City", "Tulsa"] },
  { name: "Oregon", capital: "Salem", cities: ["Salem", "Portland"] },
  { name: "Pennsylvania", capital: "Harrisburg", cities: ["Harrisburg", "Philadelphia", "Pittsburgh"] },
  { name: "Rhode Island", capital: "Providence", cities: ["Providence", "Newport"] },
  { name: "South Carolina", capital: "Columbia", cities: ["Columbia", "Charleston"] },
  { name: "South Dakota", capital: "Pierre", cities: ["Pierre", "Sioux Falls"] },
  { name: "Tennessee", capital: "Nashville", cities: ["Nashville", "Memphis"] },
  { name: "Texas", capital: "Austin", cities: ["Austin", "Houston", "San Antonio", "Dallas"] },
  { name: "Utah", capital: "Salt Lake City", cities: ["Salt Lake City", "Provo"] },
  { name: "Vermont", capital: "Montpelier", cities: ["Montpelier", "Burlington"] },
  { name: "Virginia", capital: "Richmond", cities: ["Richmond", "Virginia Beach"] },
  { name: "Washington", capital: "Olympia", cities: ["Olympia", "Seattle"] },
  { name: "Washington D.C.", capital: "District of Columbia (D.C.)", cities: ["District of Columbia (D.C.)"] },
  { name: "West Virginia", capital: "Charleston", cities: ["Charleston", "Morgantown"] },
  { name: "Wisconsin", capital: "Madison", cities: ["Madison", "Milwaukee"] },
  { name: "Wyoming", capital: "Cheyenne", cities: ["Cheyenne", "Casper"] },
];

export default STATES_DATA;